Upgrade to Weld 3
Currently the tool fails to start the CDI container with the following
error message:

```
[ERROR] Failed to execute goal
org.codehaus.mojo:exec-maven-plugin:3.0.0:java (generate-code) on
project metamodel-tests: An exception occured while executing the Java
class. WELD-001524: Unable to load proxy class for bean Implicit Bean
[javax.enterprise.inject.Instance] with qualifiers [@Default] with class
interface javax.enterprise.inject.Instance using classloader
java.net.URLClassLoader@2570b316: Could not initialize class
org.jboss.classfilewriter.ClassFile: Exception
java.lang.reflect.InaccessibleObjectException: Unable to make protected
final java.lang.Class
java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
throws java.lang.ClassFormatError accessible: module java.base does not
"opens java.lang" to unnamed module @5e407e1b [in thread
"weld-worker-7"] -> [Help 1]
```

I believe the reason for that is that the version of Weld that we use
doesn't work well with Java 11 or later. This patch updates to Weld 3 to
address that issue.

Signed-off-by: Juan Hernandez <juan.hernandez@redhat.com>